<template>
  <div class="app-container"></div>
</template>

<script>
export default {
  name: "index",
  directives: {},
  components: {},
  data() {
    return {
      list: {
        success: true,
        msg: null,
        data: [
          {
            id: "7c34769085a711e98be6525400234cf1",
            pid: null,
            mycode: "system",
            name: "系统管理",
            type: 0,
            url: "/system,Layout",
            isAppSyn: null,
            icoType: 0,
            ico: "table",
            remark: "系统管理",
            isAuthority: null,
            orderIndex: 0,
            updateName: "admin",
            updateDate: "2021-02-08T12:01:17.000+0000",
            createName: "admin",
            createDate: "2019-06-03T02:31:05.000+0000",
            isHide: 0,
            children: [
              {
                id: "fe4f168e9c1e4918a4da868fa6a08f2f",
                pid: "7c34769085a711e98be6525400234cf1",
                mycode: "menuTable",
                name: "菜单管理",
                type: 0,
                url: "/system/menu,/system/menu/index",
                isAppSyn: null,
                icoType: 0,
                ico: "list",
                remark: "菜单管理-添加-修改-删除",
                isAuthority: null,
                orderIndex: 0,
                updateName: "admin",
                updateDate: "2020-10-19T07:39:50.000+0000",
                createName: "admin",
                createDate: "2019-06-27T09:32:23.000+0000",
                isHide: 0,
                children: [],
                title: "菜单管理",
                spread: true,
                path: "/system/menu",
                component: "/system/menu/index",
              },
              {
                id: "17b0f8c1d6f14301bc740bfbb0ddd312",
                pid: "7c34769085a711e98be6525400234cf1",
                mycode: "role",
                name: "角色管理",
                type: 0,
                url: "/system/role,/system/role/index",
                isAppSyn: null,
                icoType: null,
                ico: "peoples",
                remark: "角色-新增-修改-删除 角色菜单权限管理",
                isAuthority: null,
                orderIndex: 1,
                updateName: "admin",
                updateDate: "2020-10-19T07:39:55.000+0000",
                createName: "admin",
                createDate: "2020-04-30T02:13:18.000+0000",
                isHide: 0,
                children: [],
                title: "角色管理",
                spread: true,
                path: "/system/role",
                component: "/system/role/index",
              },
              {
                id: "f77929cef86a418b96201d355345ffae",
                pid: "7c34769085a711e98be6525400234cf1",
                mycode: "wordbook",
                name: "字典管理",
                type: 0,
                url: "/system/wordbook,/system/wordbook/index",
                isAppSyn: null,
                icoType: null,
                ico: "education",
                remark: "字典管理 新增-修改-删除",
                isAuthority: null,
                orderIndex: 2,
                updateName: "admin",
                updateDate: "2020-10-19T07:40:00.000+0000",
                createName: "admin",
                createDate: "2020-05-06T06:22:37.000+0000",
                isHide: 0,
                children: [],
                title: "字典管理",
                spread: true,
                path: "/system/wordbook",
                component: "/system/wordbook/index",
              },
              {
                id: "8867efdc1a074328ae357b2bf5312b0b",
                pid: "7c34769085a711e98be6525400234cf1",
                mycode: "user",
                name: "用户管理",
                type: 0,
                url: "/system/user,/system/user/index",
                isAppSyn: null,
                icoType: null,
                ico: "user",
                remark: "用户管理 新增-修改-删除",
                isAuthority: null,
                orderIndex: 3,
                updateName: "admin",
                updateDate: "2020-10-19T07:40:06.000+0000",
                createName: "admin",
                createDate: "2020-05-06T09:51:32.000+0000",
                isHide: 0,
                children: [],
                title: "用户管理",
                spread: true,
                path: "/system/user",
                component: "/system/user/index",
              },
              {
                id: "1e710048c5574cd8bc82d614f48e47d1",
                pid: "7c34769085a711e98be6525400234cf1",
                mycode: "org",
                name: "组织机构",
                type: 0,
                url: "/system/org,/system/org/index",
                isAppSyn: null,
                icoType: null,
                ico: "zuzhijiagou",
                remark: "组织机构-新增-修改-删除",
                isAuthority: null,
                orderIndex: 4,
                updateName: "admin",
                updateDate: "2021-03-08T05:58:51.000+0000",
                createName: "admin",
                createDate: "2020-05-06T09:52:14.000+0000",
                isHide: 0,
                children: [],
                title: "组织机构",
                spread: true,
                path: "/system/org",
                component: "/system/org/index",
              },
            ],
            title: "系统管理",
            spread: true,
            path: "/system",
            component: "Layout",
          },
          {
            id: "b72a2853495048c18d4a0c7234cff5f3",
            pid: null,
            mycode: "workbench",
            name: "我的工作台",
            type: 0,
            url: "/workbench,Layout",
            isAppSyn: null,
            icoType: null,
            ico: "gongdan",
            remark: "",
            isAuthority: null,
            orderIndex: 1,
            updateName: "admin",
            updateDate: "2021-03-05T08:12:52.000+0000",
            createName: "admin",
            createDate: "2021-03-05T08:12:25.000+0000",
            isHide: 0,
            children: [
              {
                id: "dc0a23ec2e2b4a8ab69748c08fcea561",
                pid: "b72a2853495048c18d4a0c7234cff5f3",
                mycode: "myWorkbench",
                name: "我的工作台",
                type: 0,
                url: "/myWorkbench,Three",
                isAppSyn: null,
                icoType: null,
                ico: "excel",
                remark: "",
                isAuthority: null,
                orderIndex: 1,
                updateName: null,
                updateDate: null,
                createName: "admin",
                createDate: "2021-03-08T02:17:20.000+0000",
                isHide: 0,
                children: [
                  {
                    id: "fd1029f7d31f4579b43b8defc1287478",
                    pid: "dc0a23ec2e2b4a8ab69748c08fcea561",
                    mycode: "demo",
                    name: "待办任务",
                    type: 0,
                    url: "/ToDoTask,/myWork/ToDoTask",
                    isAppSyn: null,
                    icoType: null,
                    ico: "form",
                    remark: "",
                    isAuthority: null,
                    orderIndex: 1,
                    updateName: null,
                    updateDate: null,
                    createName: "admin",
                    createDate: "2021-03-08T02:23:55.000+0000",
                    isHide: 0,
                    children: [],
                    title: "demo",
                    spread: true,
                    path: "/demo",
                    component: "/demo/index",
                  }
                ],
                title: "我的工作台",
                spread: true,
                path: "/myWorkbench",
                component: "Three",
              },
            ],
            title: "我的工作台",
            spread: true,
            path: "/workbench",
            component: "Layout",
          },
        ],
        code: 1000,
      },
    };
  },
  mounted() {
    // console.log(this.list.data)
    let a = this.ck(this.list.data, []);
    // console.log(JSON.stringify(a));
  },
  created() {},

  methods: {
    ck(data, arr) {
      var that = this;
      data.forEach((ele) => {
        // console.log(ele);
        if(ele.children&&ele.children.length>0){
          ele.children = that.ck(ele.children,[])
        }
        var ad = {
          id: ele.id,
          pid: ele.pid,
          orderIndex:ele.orderIndex,
          hidden:ele.hidden,
          component: ele.component,
          name: ele.mycode,
          title: ele.title,
          path: ele.path,
          icon: ele.ico,
          children:ele.children,
          remark:ele.remark
        };
        arr.push(ad)
      });
      return arr
    },
  },
};
</script>
<style>
</style>
